--CREATE DATABASE DEPARTAMENTOS_DE_GUATEMALA

USE DEPARTAMENTOS_DE_GUATEMALA

/*CREATE TABLE DEPARTAMENTO(
Nombre VARCHAR (25) PRIMARY KEY,
Cabecera Varchar (25),
DistanciDesdeCapital DECIMAL (4,1),
Poblacion INT,
NumerodeMunicipios INT,
LugaresTuristicos TEXT,
);*/

